### ISSUE TITLE
Feature Request - Subdirectory support

### ISSUE THREAD

**Issue by Evil-Dragon** [toshiaki1729/stable-diffusion-webui-dataset-tag-editor#1]
Would it be possible to add subdirectory support to this extension? I currently have all my images saved from SD into subdirectories and it would be nice to be able to put in one path and search/filter all of them at once.

**Comment by toshiaki1729** [comment]
@Evil-Dragon
Added the feature to load dataset from subdirectories : 9e86a176719ff331280157eba55a02fcc30c2f8a
Thank you for your request!
