### ISSUE TITLE
Error when tagging selected image

### ISSUE THREAD

**Issue by Zolilio** [toshiaki1729/stable-diffusion-webui-dataset-tag-editor#100]
**Describe the bug**
Interrogator giving error when trying to interrogate selected image (tried with "wd-swinv2-tagger-v3" interrogator

**To Reproduce**
1. Go to "Dataset Tag Editor" tab
2. Select and load Dataset directory
3. Click on one of the images in the dir
4. Select "Edit Caption of Selected Image" and then "Interrogate Selected Image" tab
5. Select an Interrogator and click on "Interrogate" button
6. See error

**Expected behavior**
Give tags of the selected image in "Interrogate Result"

**Screenshots**
![Capture d’écran 2024-05-25 150559](https://github.com/toshiaki1729/stable-diffusion-webui-dataset-tag-editor/assets/63771812/446e4aeb-02b7-4982-a13f-becd21d2c873)
![Capture d’écran 2024-05-25 150622](https://github.com/toshiaki1729/stable-diffusion-webui-dataset-tag-editor/assets/63771812/78bb7173-1ee0-4d07-9292-73bd383816b1)

**Environment:**
 - OS: Windows
 - Browser: Microsoft Adge
 - Version of SD WebUI: v1.9.3
 - Version of this app: v0.3.4

**Comment by toshiaki1729** [comment]
Thank you!
