### ISSUE TITLE
WD V3 taggers cropping images.

### ISSUE THREAD

**Issue by knzro** [toshiaki1729/stable-diffusion-webui-dataset-tag-editor#101]
**Describe the bug**
wd-swinv2-tagger-v3, wd-vit-tagger-v3 and wd-covnext-tagger-v3 taggers are getting a cropped image as input.

**To Reproduce**
1 interrogate a long fullbody image.

**Expected behavior**
The image should be interrogated as normal but currently most images are getting the head out of frame and feet out of frame tags. 

For example the attached image interrogated in wd-swinv2-tagger-v3 returns: 1girl, solo, long_hair, simple_background, shirt, skirt, long_sleeves, white_background, very_long_hair, standing, school_uniform, pleated_skirt, open_clothes, green_hair, socks, character_name, sleeves_past_wrists, **feet_out_of_frame**, kneehighs, buttons, black_socks, cardigan, grey_skirt, arm_at_side, **head_out_of_frame,** pleated_dress, grey_dress, open_cardigan, brown_cardigan, lower_body, yellow_cardigan

As can be seen it mentioned the head out of frame tag. On the other hand in another implementations of wd-swinv2-tagger-v3 (https://huggingface.co/spaces/SmilingWolf/wd-tagger) it returns; 1girl, solo, green hair, long hair, school uniform, socks, full body, green eyes, bow, shoes, black socks, cardigan, white background, sneakers, kneehighs, red footwear, simple background, standing, looking at viewer, bowtie, dress, grey skirt, hair bun, red bow

As can be seen the interrogator can't see the top or bottom of the image. I tested the WDV2 interrogator and those are working fine so it is a V3 only problem

**Screenshots**

![istockphoto-1421009144-2048x2048](https://github.com/toshiaki1729/stable-diffusion-webui-dataset-tag-editor/assets/83365874/fe71cfb9-0c71-40aa-82b2-b90516a22e76)

**Environment (please complete the following information):**
 - OS: windows
 - Browser: firefox
 - Version of SD WebUI: v1.9.3, by AUTOMATIC1111
 - Version of this app: 0.3.4

**Comment by knzro** [comment]
The wd-v1-4-vit-tagger-v2 seems to be working fine but wd-v1-4-swinv2-tagger-v2 seems to be also doing some cropping.

**Comment by toshiaki1729** [comment]
I have not implemented a feature to cropping images but this extension uses Automatic1111's `images` library to resize images.
Sometimes it behaves not as same as the original implementation.

**Comment by knzro** [comment]
It is odd, the behavior seem consistent in all WD V3 models, almost all images with a large Y in the  X:Y ratio are getting the feet_out_of_frame and or head_out_of_frame tags for example for wd-vit-tagger-v3
from a dataset of 327 I am getting head_out_of_frame [79] false positives.

**Comment by knzro** [comment]
Ran a 1 to 1 comparison against the stand alone version. The stand alone doesn't present the same behavior. So it is likely A1111 is passing the extension a cropped version of the images(likely as an optimization). Why? I don't know. I guess i will use the standalone version in the meanwhile.

**Comment by toshiaki1729** [comment]
Fixed this issue by making images square before interrogating.
Maybe the image transformer (automatically created from timm config) crops image if the image is not square shaped.
