### ISSUE TITLE
Negative Filtering and / OR Add all to Filter by Selection

### ISSUE THREAD

**Issue by Rartist** [toshiaki1729/stable-diffusion-webui-dataset-tag-editor#11]
Hi,

Thanks for creating this Extension. It's a huge help.
Before I was editing the text files of my datasets per hand and that just wasn't effective at all.

Speaking of... I didn't find a way to filter *out* a tag.

2 ideas on how to implement that:

1) Clicking a Tag a second time (or Alt+Clicking) excludes that tag from the current selection (maybe the Tag is shown red in the UI) 

2) Add a "Add all" Button to "Filter by Selection" (currently you'd have to Enter in every single image that uses a tag; so that you can use "Invert Selection" afterwards)

Thanks for listening!

**Comment by toshiaki1729** [comment]
Thank you for your suggestion!

> 1. Add a "Add all" Button to "Filter by Selection" (currently you'd have to Enter in every single image that uses a tag; so that you can use "Invert Selection" afterwards)

Now available in  d9e6cc4f5de6464b2934a6f38e0dcb505b0a8e72

> 2. Clicking a Tag a second time (or Alt+Clicking) excludes that tag from the current selection (maybe the Tag is shown red in the UI)

This can be a big project so I propose adding new blacklist tab.

**Comment by toshiaki1729** [comment]
> Now available in d9e6cc4f5de6464b2934a6f38e0dcb505b0a8e72
> This can be a big project so I propose adding new blacklist tab.

Currently, you can apply filter like "NOT (a AND b)" but cannot "NOT (a OR b)".
The method 2 can make it possible, and I will try to add the feature in some form.

**Comment by Rartist** [comment]
Thanks for the implementation!

And thanks for continuing working on this great Extension!

The Datasets will just grow from here on. :)
