### ISSUE TITLE
Request: Add option to ignore Deepdanbooru weights in tag list

### ISSUE THREAD

**Issue by leppie** [toshiaki1729/stable-diffusion-webui-dataset-tag-editor#14]
Currently it lists everything as unique, so you have to edit/filter for many combinations. Scanning through the list is extremely painful even on datasets with only 20+ images. 

Current workflow is to just filter and deal with each one individually, which is tedious. 

Renaming could be an issue though, especially when exiting tags exists with different weights. 

Havent thought about how to make it work nicely though. I really like this extension, and it works extremely well, I guess you can figure it out :D

Keep up the good work.

**Comment by leppie** [comment]
The 'add all' request in #11 will relieve some of the workflow issues.

**Comment by toshiaki1729** [comment]
It's using webUI's Interrogate Options so you can filter tags by weights in `Interrogate: deepbooru score threshold` section.

Also, for I will deal with #11 #15 by adding logic switch on tag filter, and by separating batch tag replacing feature from tag filter.
I think this will improve the workflow a bit.

I want to add some interactive checkbox that allows editing the text inside, but I'm not skilled that much for now…

**Comment by toshiaki1729** [comment]
I will try to add the features to keep booru tag weights and filter by them.
I do not yet know how it will be implemented since captions cannot keep their tag weight…

**Comment by toshiaki1729** [comment]
> ignore Deepdanbooru weights
> especially when exiting tags exists with different weights.
Ah... Do you mean webUI's emphasis like (tag) or [tag] or (tag:1.2) thing, not the internal tag score?

**Comment by toshiaki1729** [comment]
Now tag scores can be configured in UI, and this issue seems not active, so I will close this.

> I will try to add the features to keep booru tag weights and filter by them.

This didn't work well. It was just complicated.
