### ISSUE TITLE
Enhancement: Allow danbooru autocomplete in edit tag field

### ISSUE THREAD

**Issue by crackfoo** [toshiaki1729/stable-diffusion-webui-dataset-tag-editor#17]
Hi, 

It is possible to allow the booru tag autocomplete extension to get used (if installed/enabled) in the edit caption fields?

https://github.com/DominikDoom/a1111-sd-webui-tagcomplete

Thanks!

**Comment by toshiaki1729** [comment]
As long as I checked how the extension works, It's searches only prompt textboxes in txt2img and img2img tabs.

In `tagAutocomplete.js` line 862;
```Javascript
// Find all textareas
let txt2imgTextArea = gradioApp().querySelector('#txt2img_prompt > label > textarea');
let img2imgTextArea = gradioApp().querySelector('#img2img_prompt > label > textarea');
let txt2imgTextArea_n = gradioApp().querySelector('#txt2img_neg_prompt > label > textarea');
let img2imgTextArea_n = gradioApp().querySelector('#img2img_neg_prompt > label > textarea');
let textAreas = [txt2imgTextArea, img2imgTextArea, txt2imgTextArea_n, img2imgTextArea_n];
```

Modifying the [tagcomplete](https://github.com/DominikDoom/a1111-sd-webui-tagcomplete) code is needed to use the feature in tag-editor extension.

**Comment by crackfoo** [comment]
oh ok!

Thanks, sorry to bother you. I'll see if they can update it on their side.
