### ISSUE TITLE
Extension crash when selecting an image and trying any interaction (filter, caption)

### ISSUE THREAD

**Issue by flotos** [toshiaki1729/stable-diffusion-webui-dataset-tag-editor#18]
Hi, I have images with a .txt file for each, and after updating right now the extension I get an error when I try to apply a caption 

With this error :
```
 img_paths, _ = dataset_tag_editor.get_filtered_imgpath_and_tags(filters=[path_filter, tag_filter, tag_filter_neg])
TypeError: DatasetTagEditor.get_filtered_imgpath_and_tags() got an unexpected keyword argument 'filters'
```

And this red error before doing any interaction (excepted selecting an image)
![image](https://user-images.githubusercontent.com/5550556/205916403-792e3c1e-661e-4239-b68f-96658157d2d7.png)

**Comment by toshiaki1729** [comment]
Can you check the followings?
1. The commit hash is the same as latest one (3c5987e588ad780f6799c2495b4162c9b6fb22bc)?
2. Have you reboot the webUI after update this extension? The webUI cannot reload whole scripts of this extension.

Thank you.

**Comment by flotos** [comment]
I indeed had the latest commit, clicked to "apply and restart UI", but it worked only when I rebooted automatic1111 `webui-user.bat`.

Thanks
