### ISSUE TITLE
Clear Selected Tags without Clearing Tag Filters

### ISSUE THREAD

**Issue by Rartist** [toshiaki1729/stable-diffusion-webui-dataset-tag-editor#19]
Heya again,

I saw that you are working on replacing words in tags - great! :D 

Furthermore I think it could be helpful to be able to clear the "Selected Tag" without Clearing the "Tag Filters". Currently I have found no way to do that. 
Basically this means when I filter all my tags for something like "frisbee" and I get 12 different  BLIP tags and edit one of them it stops appearing in the Tag Filter and thus I can't simply deselect it, which in turn means I have to clear Tag Filters, write "frisbee" again and repeat... a dozen times. 
Replace will of course alleviate this somewhat, but I think even afterwards there will be cases in which this functionality will be useful.

Thanks for listening.

**Comment by toshiaki1729** [comment]
Sorry for the delay in adding the features but I'm currently rebuilding the entire extension.
As you know, I'm trying to add a batch text replacement feature (#13) that will allows you to select a search range, such as the selected tags or the entire captions.
Also, I'm adding the features to choose logic to filter the tags (#15).
These features can allow you to select multiple tags to edit at once (by using OR logic)!

**Comment by Rartist** [comment]
Thank you. I'm looking forward to that.
