### ISSUE TITLE
Auto-fill "Edit Caption"

### ISSUE THREAD

**Issue by Rartist** [toshiaki1729/stable-diffusion-webui-dataset-tag-editor#23]
Every now and then I forget to "Copy and overwrite" tags to the "Edit Caption" area once I selected an image.
Also quite often I forget to do that when I still have the tag of an old image selected.

I have two ideas to make this more fluent and hopefully more "fail safe":

1) Auto-fill "Edit Caption" with the caption of the selected image (if "Edit Caption" is empty)

2) Clear "Edit Caption" after "Apply Changes to selected Image"

Thanks for listening.

**Comment by Rartist** [comment]
You work fast. Thank you!

Another thought - "Caption of selected image" doesn't clear when no image is selected.

**Comment by toshiaki1729** [comment]
> Another thought - "Caption of selected image" doesn't clear when no image is selected.

Thank you so much!
The time to debug the javascript file which I don't know much about!

**Comment by toshiaki1729** [comment]
> Another thought - "Caption of selected image" doesn't clear when no image is selected.

I cannot explain why but it is fixed with a tiny change.

**Comment by toshiaki1729** [comment]
The button is displayed in front of div class and click event wasn't sent?
I don't know much about html.

**Comment by toshiaki1729** [comment]
About the commit: e743f736fbfbe1d53da6588dec7d4705920f8c86
Actually, I wanted to observe changes in gallery content by MutationObserver (because it seems smart), but it makes the app really slow :(.

**Comment by Rartist** [comment]
I see what you mean. I often have to click Tags twice now until the list of images updates.

**Comment by Rartist** [comment]
It works great now. Clears right away.
