### ISSUE TITLE
Negative Filter Default "Or"

### ISSUE THREAD

**Issue by Rartist** [toshiaki1729/stable-diffusion-webui-dataset-tag-editor#24]
I suggest setting the Negative Filter Default to "Or", because that feels like the most natural use - to filter out all images with the selected Tags.

p.s.:

It would be great to also have "Copy caption from selected images automatically" default to True.
I for example need it every time I use the extension. Of course if the mayority of users doesn't, that would make my point void.

Maybe you could add a "user_settings" file so we can change the defaults without losing our changes every commit? (I also defaulted backups to False because they conflicted with DB iirc)

**Comment by toshiaki1729** [comment]
Now added new feature to save settings in commit a5d721998265ec8a594967a467a4262d386bd620!
Every settings on the UI will be stored.
The settings will be stored in `config.json` under the tag-editor's root folder.
