### ISSUE TITLE
Warn if "Edit Caption" has not been saved

### ISSUE THREAD

**Issue by Rartist** [toshiaki1729/stable-diffusion-webui-dataset-tag-editor#26]
Hey there,

When you select an image, edit the caption and then click a different image the "Edit Caption" part gets overridden of course (which is good). 

Is there some way to ask the user to save the edited caption if he has not? ("Edit Caption" =! "Caption of Selected Image" as a check for example)

**Comment by toshiaki1729** [comment]
I found a way to do it with gradio, but it may be complicated;
1. [javascript] detect change of image selection and send click event to hidden button (same as doing currently)
1. [python gradio] on callback of the click event, evaluate "Edit Caption" != "Caption of Selected Image" ->A, and send A to hidden checkbox X
1. [python gradio] before callback of X change event, call javascript code to show confirm dialog saying like "Save change on the caption?" (if A is True), and send the following result to the callback
1. [javascript] if user selected Cancel or A is False, return False, else return True  -> B
1. [python gradio] on callback of X, save changes if B is True, and update caption depending on selected image

**Comment by toshiaki1729** [comment]
Please consider the above enigmatic text as my personal note.
I will add the feature later.

**Comment by toshiaki1729** [comment]
Thank you for your suggestion!

**Comment by Rartist** [comment]
Thank *you* for implementing my suggestions! :)
