### ISSUE TITLE
Request: Quickly deleting tags

### ISSUE THREAD

**Issue by magpie514** [toshiaki1729/stable-diffusion-webui-dataset-tag-editor#28]
Excuse me if I'm operating this wrongly, but it seems difficult to remove tags from images.
Right now you have to select them one by one, which will allow them to show up in "batch edit captions" but ONLY if they are common to all selected images.
Since I want to remove false negatives from random images, they tend to not be shared, making deleting the tags very difficult, as they need to be removed one by one.
Can there be a "remove selected tags" button of sorts? That'd allow cleaning up those stray tags without having to do it manually one by one in the text files.

**Comment by toshiaki1729** [comment]
Currently, the following is the way to delete many tags at once.

1. If you want to limit the images to remove tags from, use "Filter by Selection".
1. Select the tags to delete in "Filter by Tags" with OR logic.
1. In "Batch Edit Captions", set "Search Text" = ".+", "Replace Text" = "", check "Use regex", select "Only Selected Tags", and click "Search and Replace".

**Comment by toshiaki1729** [comment]
I think it's complicated, so I will add the dedicated tab to delete tags.

**Comment by magpie514** [comment]
This is fantastic, it's really fast to remove stray tags now! Thank you very much.
