### ISSUE TITLE
Error while loading tag editor

### ISSUE THREAD

**Issue by RicketySplit1** [toshiaki1729/stable-diffusion-webui-dataset-tag-editor#29]
Hi, I'm running into this error when booting up the webui after doing a recent update:

```
Error loading script: main.py
Traceback (most recent call last):
  File "C:\SD\stable-diffusion-webui-Automatic1111\modules\scripts.py", line 195, in load_scripts
    module = script_loading.load_module(scriptfile.path)
  File "C:\SD\stable-diffusion-webui-Automatic1111\modules\script_loading.py", line 13, in load_module
    exec(compiled, module.__dict__)
  File "C:\SD\stable-diffusion-webui-Automatic1111\extensions\stable-diffusion-webui-dataset-tag-editor\scripts\main.py", line 11, in <module>
    from scripts.dataset_tag_editor.ui import TagFilterUI, TagSelectUI
ImportError: cannot import name 'TagSelectUI' from 'scripts.dataset_tag_editor.ui' (C:\SD\stable-diffusion-webui-Automatic1111\extensions\stable-diffusion-webui-dataset-tag-editor\scripts\dataset_tag_editor\ui.py)
```

**Comment by toshiaki1729** [comment]
Hmm... It seems to try importing module in right way.
Can you check if the commit hash of your tag editor is up to date and starting with 9f6656ff3d3578e139209a3bb0accb56d25396b4, by running following command on tag-editor root dir?
```
git rev-parse HEAD
```

**Comment by toshiaki1729** [comment]
And please close webui-user.bat and restart if you didn't after updating tag-editor.
webui cannot reload entire scripts of this extension for now.

**Comment by RicketySplit1** [comment]
The hash is 9f6656ff3d3578e139209a3bb0accb56d25396b4.

**Comment by RicketySplit1** [comment]
Okay it seems that restarting it did the trick.

**Comment by toshiaki1729** [comment]
>webui cannot reload entire scripts of this extension for now.
Now hot-reload feature is enabled on the commit 9bea5f502e2018b2c7d6156fcee9a1f9366bf1a5!
