### ISSUE TITLE
Filter by tag doesn't change displayed images

### ISSUE THREAD

**Issue by WildSlowpoke** [toshiaki1729/stable-diffusion-webui-dataset-tag-editor#31]
Maybe I'm not understanding the usage of filter by tag, but when I use it, none of my images are being filtered. I know I can use it for editing tags, but I was under the impression that it would filter the images kind of like the filter by selection tab does.

**Comment by toshiaki1729** [comment]
Can you find any errors on your browser console?
You can check it by pushing F12.

**Comment by toshiaki1729** [comment]
oops I confirmed same behavior.
I am trying to find why it is happening.

**Comment by toshiaki1729** [comment]
Sorry for your inconvenience!!
It was because Enum class object had to be a single instance but it was not.

**Comment by WildSlowpoke** [comment]
No worries, thanks for the update!
