### ISSUE TITLE
[Question] Automatically tag all files without a caption file?

### ISSUE THREAD

**Issue by magpie514** [toshiaki1729/stable-diffusion-webui-dataset-tag-editor#32]
Hello! I've found this extension to be excellent when editing files already captioned, but I'm trying to caption a fresh data set without using the standard image preparation in webui and I am a bit lost, I'm not sure if it's possible.
What I mean is automatically interrogate all files without a caption txt file, is this something that can be done, or can only be done one by one?

**Comment by toshiaki1729** [comment]
As in the Train tab of webUI, the interrogators can be used by setting "Use Interrogator Caption" to something other than "No".
![ss](https://user-images.githubusercontent.com/116595002/210998683-4ec802ae-78dc-4c4e-b1ea-5e9335c6c6c0.png)

**Comment by magpie514** [comment]
Interesting, I was sure I tried that, but seems I needed to use "overwrite" instead for it to actually work! 
Thank you very much, I'll close the issue now since it was user error.
Now that LoRA training is accessible this extension is absolutely essential, thanks a lot for making it as well!

**Comment by toshiaki1729** [comment]
I noticed "If Empty" is not working well, and fixed in 768c3f36aa03c618569ae659e531f9e9bd8ce97f

**Comment by magpie514** [comment]
Ah! Maybe I ran into that, good to know! Thanks again!
