### ISSUE TITLE
Request: add more captioning

### ISSUE THREAD

**Issue by mykeehu** [toshiaki1729/stable-diffusion-webui-dataset-tag-editor#33]
I suggest adding new captioner models, because, for example, GIT-Large is already doing a very good job. I also suggest adding Nielsr's captioners to expand the possibilities:
https://huggingface.co/spaces/nielsr/comparing-captioning-models

**Comment by toshiaki1729** [comment]
It seems the current version of [transformers](https://github.com/huggingface/transformers) in webUI is not compatible with the GIT model.
I'm trying to find the solution.

**Comment by toshiaki1729** [comment]
I tried with some images, and GIT-large-coco seemed to be unstable for captioning.
GIT-base-coco may be better for now.
![ss](https://user-images.githubusercontent.com/116595002/212364193-8d12e9fb-481a-4de0-a5db-0185f1c86bcd.png)

> It seems the current version of [transformers](https://github.com/huggingface/transformers) in webUI is not compatible with the GIT model.
> I'm trying to find the solution.

`pip install --upgrade git+https://github.com/huggingface/transformers` will be needed to use the GIT.
This changes the transformer version of webUI into a development version, which may conflict with webUI and other extensions.

**Comment by mykeehu** [comment]
For me, GIT-large has given me good tags several times, but sometimes I've had to pick and choose from the others. But GIT-large was good several times. But having more choice is good, isn't it? :)
I'm not a developer, but is it possible that there are multiple versions of transformers up and you call the appropriate one when generating? I had a few crashes recently due to incompatibilities, and deleted the venv folder, since then my webUI is not completely stable.

**Comment by toshiaki1729** [comment]
Yes, DreamBooth extension changes the transformer version of webUI.
On the startup webui-user.bat, webUI changes the version into 4.19.2, and DreamBooth changes it into 4.25.1.
This is why the startup is too slow when DreamBooth is enabled.

When I added;
> pip install --upgrade git+https://github.com/huggingface/transformers will be needed to use the GIT.

The battle will be held among some extensions.
The order in which extensions are loaded depends on the folder name, so it is not clear which version will be used.

**Comment by toshiaki1729** [comment]
> I'm not a developer, but is it possible that there are multiple versions of transformers up and you call the appropriate one when generating?

I'm not very familiar with python or pip, but it seems changing folder name in venv works.
https://stackoverflow.com/questions/33208597/using-same-library-with-different-version-across-virtual-environment
But I'm not sure it's a "legal" way.

**Comment by toshiaki1729** [comment]
official release on huggingface.
I will implement this captioning when webUI bump up the transformers version from 4.25.1 to 4.26.0 or higher.
https://github.com/huggingface/transformers/releases/tag/v4.26.0

**Comment by toshiaki1729** [comment]
>I'm not very familiar with python or pip, but changing folder name in venv seems to work.
>https://stackoverflow.com/questions/33208597/using-same-library-with-different-version-across-virtual-environment

I tried this in some different ways (like downloading in different folder, modifying python importing method), but I couldn't use new transformers without overwriting venv.
Waiting for change in webUI.

**Comment by Infinitay** [comment]
Additionally, BLIP2 was released recently and it would be a nice addition. I believe they are working on implementing BLIP2 into the HuggingFace library currently.

https://github.com/salesforce/LAVIS/tree/main/projects/blip2

**Comment by toshiaki1729** [comment]
BLIP2 on transformers
https://github.com/huggingface/transformers/releases/tag/v4.27.0

It's already available from LAVIS though.
