### ISSUE TITLE
 " [ ] " is not loaded anymore

### ISSUE THREAD

**Issue by Rartist** [toshiaki1729/stable-diffusion-webui-dataset-tag-editor#34]
Hey there,

First off - I really like how you handled the last few additions to this Extension.

For a while now my folders didn't load anymore though. 
At first I thought it was a bug and redownloaded the Extension.

Turns out the name of my folders was the problem. I have the bad habit of naming folders with "[Name]" every now and then and apparently the square brackets prevent the Tag Editor from loading a folder now (it worked before, like a month or two ago).

Is there a way around this?

**Comment by toshiaki1729** [comment]
Thank you very much for your report.
Fixed by escaping the brackets in directory.
