### ISSUE TITLE
Close Selected Image after "Apply Changes" and Clear Empty Tag(s)

### ISSUE THREAD

**Issue by Rartist** [toshiaki1729/stable-diffusion-webui-dataset-tag-editor#35]
I'm quite sure that functionality was how it worked in an older version.

The request is basically in the title:

Please close the selected Image once "Apply Changes" is clicked. Also please clear an empty Tag "[0]" from selected Tags once it's removed.

p.s.:
Also clear the selected Image after such actions as "Apply Selection Filter". Currently it often still shows a wrong formerly selected Image after applying a Selection Filter.

Thanks.

**Comment by toshiaki1729** [comment]
Thank you so much for your reporting!
These great features were implemented unconsciously, and some changes like edcfadbdd7df4c113db111cf437292b8a5116119 or 6c3e80ba2e6ebe5a99b8c8b556b569a2f9d5b2c5 might disabled them.
