### ISSUE TITLE
2 ideas

### ISSUE THREAD

**Issue by Rartist** [toshiaki1729/stable-diffusion-webui-dataset-tag-editor#37]
Hey there,

1) What do you think about moving "Remove selected Tags" to  "Filter by Tags" under "Filter Logic", but on the right side (so it doesn't get clicked by mistake.
-> when I check for and want to remove tags I need to hop around between "Filter" and "Remove" a LOT, because I need to check if they are actually wrong first (remove won't show selected tags / images) and THEN hop to "Remove" to find them again (a lot of fun with several hundred tags), select them again and then remove them. This feels unecessarily complicated. A simple button to delete selected Tags would be all that is needed. Now either "Remove Duplicated" could be moved to "Search and Replace" or kept under "Remove", beacuse atm I'm not sure where "Select / Deselect Visible Tags" would fit better.

Please consider this.

2) With big Datasets and several hundred tags it's hard to keep track of where you are while curating & removing tags.
Right now I am trying to reduce the shown tags by going from writing "a" or "b" etc. in the filter, but that still shows all tags with "a" or "b". To show words that start with the selected letter (or number?) only would be very much appreciated.
This could either be a "Tag Prefix Filter" Button or maybe some kind of Regex?

Thanks for listening, keep up the good work!

**Comment by toshiaki1729** [comment]
Thank you for your suggestions!

> 1. What do you think about moving "Remove selected Tags" to "Filter by Tags" under "Filter Logic", but on the right side (so it doesn't get clicked by mistake.
> …

I think the tags would need to be removed in the following cases:
1. Some images contain some unnecessary tags for entire dataset.
1. Some images contain some unnecessary tags, but the tags themselves are appropriate for other images.

And the fastest way would be the followings:
case 1:
&emsp;In batch remove tab, select the tags and click "Remove selected tags" without any filter.
case 2:
&emsp;Add images containing unnecessary tags to selection filter and apply. This can be done easily with tag filter: filter by tag of interest, select inappropriate image, and hit [Enter] key.
&emsp;Then, remove the tags as in case 1.

**Comment by toshiaki1729** [comment]
> 2. With big Datasets and several hundred tags it's hard to keep track of where you are while curating & removing tags.
> …

I will add simple prefix/suffix option and regex feature on "Search Tags"!
