### ISSUE TITLE
Custom Temp Folder Location

### ISSUE THREAD

**Issue by Rartist** [toshiaki1729/stable-diffusion-webui-dataset-tag-editor#38]
Hi toshiaki,

Please let the user specify a custom Temp Folder or use the Temp Folder specified in the A1 settings. Thanks.

**Comment by toshiaki1729** [comment]
Thank you for your suggestion!
As far as I know, this extension was using only temp files which are created automatically by gradio gallery.
It was completely wasting storage, so I changed the code to use webUI's custom image loader, not to make temp files.
