### ISSUE TITLE
[WinError 32] The process cannot access the file because it is being used by another process

### ISSUE THREAD

**Issue by seicocat** [toshiaki1729/stable-diffusion-webui-dataset-tag-editor#39]
https://i.imgur.com/uKHpJDn.png

Getting this error when trying to move images+captions to a different folder after updating to latest commit.

**Comment by toshiaki1729** [comment]
Sorry for inconvenience!
I forgot releasing loaded images from memory when replace or delete the file itself…

**Comment by seicocat** [comment]
> Sorry for inconvenience! I forgot releasing loaded images from memory when replace or delete the file itself…

no problem thanks for your hard work!
