### ISSUE TITLE
Feature Request: Limit access only to folders stored in SD installation folder

### ISSUE THREAD

**Issue by nanodesuP** [toshiaki1729/stable-diffusion-webui-dataset-tag-editor#4]
This extension is extremely helpful. Thank you so much.
But one thing is questionable. As of now you can access any folder, and with subdirectory support just C:\ is enough to see all images stored on that particular drive. This could be unsafe when sharing your SD installation with others.
Optional feature limiting access to images stored in SD installation folder would be great.

**Comment by toshiaki1729** [comment]
@nanodesuP 
Thank you for your suggestion but I don't think the limitation is necessary.
I'm not sure about other OSes but on Windows, the access to the files of other users will be denied unless you've already got permission.
This extension uses standard Python os modules to access files, and its behavior is same as that of OS.

- The results when access other user's file.
I added some code to print paths accessed and exception messages for debug.
![ss1](https://user-images.githubusercontent.com/116595002/201080751-5cdbfba8-ad90-45a0-b8c4-1aa116425769.png)
![ss2](https://user-images.githubusercontent.com/116595002/201080794-72423a89-749d-4da5-8f24-1d0b12627e22.png)

- The result of loading files from "C:\" including subdirectories on my PC.
The loading is aborted when tried to access the directory without permission.
![ss3](https://user-images.githubusercontent.com/116595002/201084284-9f5263aa-73ca-490d-b0dc-840a5a6a24c1.png)

**Comment by toshiaki1729** [comment]
I think adding the following features will be good intending to prevent accidents (might be happen when I'm drunk or sleepy).

- Directory Whitelist
- Button to cancel unwanted loading

But it will be still **not safe** because any user still can access any files with permission as same as file explorer can do, by disabling these options or editing source code.
