### ISSUE TITLE
ModuleNotFoundError: No module named 'onnxruntime'

### ISSUE THREAD

**Issue by ride5k** [toshiaki1729/stable-diffusion-webui-dataset-tag-editor#43]
running auto1111 AMD fork, installed from extensions pull

arch: AMD64
cpu: AMD64 Family 25 Model 80 Stepping 0, AuthenticAMD
system: Windows
release: Windows-10-10.0.19045-SP0
python: 3.10.6
xformers: unavailable
accelerate: 0.12.0
transformers: 4.25.1
Stable Diffusion: (unknown)
Taming Transformers: [2426893] 2022-01-13
CodeFormer: [c5b4593] 2022-09-09
BLIP: [48211a1] 2022-06-07
k_diffusion: (unknown)

**Comment by toshiaki1729** [comment]
The commit c0aa72e100ae5647a24f9bd4163f02835d9d7aef may fix this issue, however, it is tested only with nvidia GPU since I don't have AMD one.

**Comment by toshiaki1729** [comment]
Sorry I forgot to make the DirectML to be used.
Fixed in 9db35c0a45a283a355a33e27119cffb982ca7e83.

**Comment by toshiaki1729** [comment]
Is this issue fixed?
