### ISSUE TITLE
ValueError: Cannot process type as image: <class 'pathlib.WindowsPath'>

### ISSUE THREAD

**Issue by RubyXGit** [toshiaki1729/stable-diffusion-webui-dataset-tag-editor#45]
I'm getting this error when trying to use the "Add selection" or "Add ALL Displayed" buttons in the "Filter by Selection" tab.
Using the latest commits of automatic1111 and this extension as of today.
OS is Windows 11.

**Comment by toshiaki1729** [comment]
Thank you for reporting!
