### ISSUE TITLE
Unclear how sorting algorithm works in the Batch Edit Captions - Extra Tab

### ISSUE THREAD

**Issue by DKnight54** [toshiaki1729/stable-diffusion-webui-dataset-tag-editor#46]
There's no description of how the tags are sorted when using this feature. Additionally, given the importance of tag order to focus training, especially when preparing tags for lora training, it would be helpful to have a feature where the user can arrange all available tags into a preferred order, and then sort the tags based on the order.

**Comment by toshiaki1729** [comment]
https://github.com/toshiaki1729/stable-diffusion-webui-dataset-tag-editor/pull/41

**Comment by toshiaki1729** [comment]
Now I'm refactoring UI and the changing sort algorithm feature will be added later.
