### ISSUE TITLE
Features: load images even if no txt files / interrogate option

### ISSUE THREAD

**Issue by crackfoo** [toshiaki1729/stable-diffusion-webui-dataset-tag-editor#5]
Hi, 

Sometimes there are images in a folder that don't have a txt file with them and they arn't seen. Is it possible to include them, so then it would be possible to add the approprite tags and create the txt file when the tags are saved?

Also, could adding the interrogate option be an option to prefill the tags?

Thanks!

**Comment by toshiaki1729** [comment]
> However, I'm not sure if it will be useful, since the only images having filenames consisting of only numbers and hyphens (or only file extension) are determined to have no caption.

Ah, I think adding option to disable loading caption from filename will be good.

**Comment by crackfoo** [comment]
Ok, tested it and it does now show images without a txt file, as long as they are PNG anyway. Can it allow jpg/jpeg?

regarding interrogate, I was thinking perhaps it's possible to use the same type of interrogate that is used in the pre-process images tab? But seems is mostly redundent feature since it's already somewhere else

**Comment by toshiaki1729** [comment]
> Can it allow jpg/jpeg?

Now this extension reads the files the same way as in Train tab, and allows image files supported by Pillow library such as jpg, png, bmp, psd, tiff, and so on.
Actually, the current method is just a first-aid and redundant, so I will fix it.

> regarding interrogate, I was thinking perhaps it's possible to use the same type of interrogate that is used in the pre-process images tab? But seems is mostly redundent feature since it's already somewhere else

Initially, this extension was only intended to assist in editing captions created with deepbooru interrogator.
However, if there seem to be similar requests, I will try to add the feature.
