### ISSUE TITLE
Filter by tag doesn't change displayed images (again?)

### ISSUE THREAD

**Issue by slashedstar** [toshiaki1729/stable-diffusion-webui-dataset-tag-editor#56]
Same as https://github.com/toshiaki1729/stable-diffusion-webui-dataset-tag-editor/issues/31
I need to select the tags, switch to filter by selection tab and hit "apply selection filter", I hope this isn't intended since it becomes quite laborious to quickly scan tags.
[localhost-1678395572464.log](https://github.com/toshiaki1729/stable-diffusion-webui-dataset-tag-editor/files/10936028/localhost-1678395572464.log)

**Comment by toshiaki1729** [comment]
I couldn't reproduce your error.
However, given the circumstances, the errors seems to be saying cannot update (invisible) Checkboxes which are used to change visibility of images in gallery.
I'm not sure but the change from gradio.CheckboxGroup to gradio.State may solve this… I hope so.

**Comment by toshiaki1729** [comment]
> Anyway, in the next commit I will change tag-editor to use gradio.State and ask you if the issue is fixed.

gradio.State couldn't use as input of javascript code…

**Comment by slashedstar** [comment]
Seems like it was just the webui being finnicky again, even after a restart it was behaving the same, but now somehow the error is cleared up 👍
