### ISSUE TITLE
Feature Request: add CLIP and Deepbooru interrogators

### ISSUE THREAD

**Issue by mykeehu** [toshiaki1729/stable-diffusion-webui-dataset-tag-editor#6]
I like this addition a lot, but it would be much better if the Edit Caption tab had CLIP and Deepbooru interrogator buttons available for the selected image (like the Img2Img tab, you could copy from there). So the captured text could be included in the Edit Caption field. This way it could be easily rewritten, or modified, or replaced again.

**Comment by toshiaki1729** [comment]
Thank you so much for your suggestion.
I will try to add interrogator feature, including the one @crackfoo mentioned in #5.

**Comment by mykeehu** [comment]
Thank you very, very much for putting it in!

**Comment by crackfoo** [comment]
thanks for this. I did update auto and the extention but recieve this error when restarting after restarting the gui:

`Reloading custom scripts
Error loading script: dataset_tag_editor_ui.py
Traceback (most recent call last):
  File "C:\Users\me\sd\forks\auto1111\modules\scripts.py", line 164, in load_scripts
    module = script_loading.load_module(scriptfile.path)
  File "C:\Users\me\sd\forks\auto1111\modules\script_loading.py", line 13, in load_module
    exec(compiled, module.__dict__)
  File "C:\Users\me\sd\forks\auto1111\extensions\stable-diffusion-webui-dataset-tag-editor\scripts\dataset_tag_editor_ui.py", line 5, in <module>
    from dataset_tag_editor import DatasetTagEditor, interrogate_image_clip, interrogate_image_booru, InterrogateMethod
ImportError: cannot import name 'interrogate_image_clip' from 'dataset_tag_editor' (C:\Users\me\sd\forks\auto1111\extensions\stable-diffusion-webui-dataset-tag-editor\dataset_tag_editor.py)`

**Comment by toshiaki1729** [comment]
@crackfoo 
Thank you for your report!
I changed folder structure in the commit 4a14c054eaf8f4ee603de29d7f417fd1dc6819de.
I hope this change fixes the problem.

**Comment by crackfoo** [comment]
works like a charm now!

Thanks!
