### ISSUE TITLE
Bug: Error when remove tags in batch mode

### ISSUE THREAD

**Issue by mykeehu** [toshiaki1729/stable-diffusion-webui-dataset-tag-editor#60]
I have generated images with the following text:
```
a medium shot of a red wavy haired girl with blue eyes naked in the classic house, smile, front shot, highly detailed eyes, super highly detailed face, detailed body, pubic hair, professional digital painting, artstation, Unreal Engine 5, HD quality, 8k resolution, beautiful, cinematic, art by artgerm
Negative prompt: lowres, bad anatomy, bad hands, text, error, missing fingers, extra digit, fewer digits, cropped, worst quality, low quality, normal quality, jpeg artifacts, signature, watermark, username, blurry, fat, bad_hands_5, squint, cross-eyes, coloured pubic hair
Steps: 30, Sampler: DPM++ 2M Karras, CFG scale: 7, Seed: 1451586861, Size: 512x512, Model hash: 712391dc4d, Model: Photo and graphic_galaxytimemachinesGTM_v3, ENSD: 31337, Score: 7.13
```

Previously in batch mode I selected all tags and unchecked what I didn't need. Now I get an error in this operation, the console says that this is the problem:
```
[tag-editor] Loading dataset from H:\Stable-Diffusion-Automatic\DreamArtist-Texture Inversion Embedding-Lora\krisztinmyperson\train
[tag-editor] Total 750 files under the directory including not image files.
[tag-editor] Loading Completed: 375 images found
Traceback (most recent call last):
  File "H:\Stable-Diffusion-Automatic\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 337, in run_predict
    output = await app.get_blocks().process_api(
  File "H:\Stable-Diffusion-Automatic\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1015, in process_api
    result = await self.call_function(
  File "H:\Stable-Diffusion-Automatic\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 833, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "H:\Stable-Diffusion-Automatic\stable-diffusion-webui\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "H:\Stable-Diffusion-Automatic\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "H:\Stable-Diffusion-Automatic\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "H:\Stable-Diffusion-Automatic\stable-diffusion-webui\extensions\stable-diffusion-webui-dataset-tag-editor\scripts\ui\block_tag_select.py", line 89, in cbg_tags_changed
    self.selected_tags = set(dte_instance.read_tags(cbg_tags))
  File "H:\Stable-Diffusion-Automatic\stable-diffusion-webui\extensions\stable-diffusion-webui-dataset-tag-editor\scripts\dataset_tag_editor\dte_logic.py", line 111, in read_tags
    tags = [re_tags.match(tag).group(1) for tag in tags if tag]
  File "H:\Stable-Diffusion-Automatic\stable-diffusion-webui\extensions\stable-diffusion-webui-dataset-tag-editor\scripts\dataset_tag_editor\dte_logic.py", line 111, in <listcomp>
    tags = [re_tags.match(tag).group(1) for tag in tags if tag]
AttributeError: 'NoneType' object has no attribute 'group'
```

Probably does not handle Enter/Paragraph in the text. You might want to include an Enter cleanup switch/preprocessor.

Before:
![image](https://user-images.githubusercontent.com/6390413/226822176-50bf744f-7696-4b52-9360-63ffad40896b.png)

After:
![image](https://user-images.githubusercontent.com/6390413/226822244-832598b3-d398-4fe6-9526-e7a189d6f89b.png)

**Comment by mykeehu** [comment]
With the batch file below, I replaced the Enter with a comma, and after that the extension didn't crash anymore, which is why I thought of an extra button to clean up the files. ChatGPT wrote me this .bat file that I run alongside the txt's:

```
@echo off
setlocal enabledelayedexpansion

for %%f in (*.txt) do (
    set "content="
    for /f "usebackq delims=" %%i in ("%%f") do set "content=!content!%%i, "
    echo !content:~0,-2! > "%%f"
)

```

**Comment by toshiaki1729** [comment]
![ss5](https://user-images.githubusercontent.com/116595002/227066270-d806cd3e-58f0-4913-adc5-eaf7416ed85c.png)

You also can use this way. This replaces all CR and LF in the displayed images with a comma (=separator in this extension).

**Comment by toshiaki1729** [comment]
Added the feature to do the same thing on loading.

**Comment by mykeehu** [comment]
Thanks for the tip and the development!

**Comment by mykeehu** [comment]
The patch works fine, the extension didn't crash, but the filtering doesn't work on Dataset images for some reason. Even if I check any tag, it does not filter. The tag filter does not work.

**Comment by toshiaki1729** [comment]
This small example worked well.
Can you provide more detailed conditions under which the filter fails?

<details>
<summary>Files (click to open)</summary>
<img src='https://user-images.githubusercontent.com/116595002/227397969-ba22a915-c5a7-48a6-b5b2-ae9837767061.png' />
</details>

<details>
<summary>Results</summary>
<img src='https://user-images.githubusercontent.com/116595002/227397932-c133c443-d8aa-40cd-ac1b-8c5013421985.png' />
<img src='https://user-images.githubusercontent.com/116595002/227397939-d81011d3-fbe1-4eff-b9f0-9a3698097846.png' />
<img src='https://user-images.githubusercontent.com/116595002/227397951-154ba70d-257e-4566-9f74-5d5b2c8ad870.png'>
</details>

**Comment by mykeehu** [comment]
If it's working for you, it might be a conflict with one of the extensions, but that's how it looks for me now.

Without filtering:
![image](https://user-images.githubusercontent.com/6390413/227441866-bbbcc1e1-b0e2-449c-95bb-b9db648637d3.png)

After filters:
![image](https://user-images.githubusercontent.com/6390413/227442233-92c6224a-b97e-4c20-8621-7c1e3379dafd.png)

![image](https://user-images.githubusercontent.com/6390413/227442346-baf59862-2fe0-4e6f-b63c-34338929236f.png)
