### ISSUE TITLE
Filter is not working with new gradio 3.23.0

### ISSUE THREAD

**Issue by toshiaki1729** [toshiaki1729/stable-diffusion-webui-dataset-tag-editor#63]
It seems that something like structure of the gallery changed.
It is working internally, but not visually.

**Comment by toshiaki1729** [comment]
noticed when fixing #62

**Comment by blckglz** [comment]
From what I can see it is not just visually bugged, e.g. the search and replace doesn't change the .txt files and the interrogate tab cannot read the file contents

**Comment by toshiaki1729** [comment]
This extension is heavily depending on the structure of the actual html displayed.
Changing the javascript code to adopt new gradio can solve most of problems… I really hope so.

**Comment by toshiaki1729** [comment]
And I think the change will make it incompatible with the older webUI.

**Comment by toshiaki1729** [comment]
> From what I can see it is not just visually bugged, e.g. the search and replace doesn't change the .txt files and the interrogate tab cannot read the file contents

It seems all of the old type hints cannot be used, not only those making errors like #62.

**Comment by toshiaki1729** [comment]
I think the filters and other features can be used now.
But the filter became slower than the previous version.
