### ISSUE TITLE
"Read caption from selected image" and "Interrogate selected image" sub tab not working.

### ISSUE THREAD

**Issue by Vigilence** [toshiaki1729/stable-diffusion-webui-dataset-tag-editor#66]
After the newest update the "Read caption from selected image" and "Interrogate selected image" sub tab, which is under the "Edit caption from selected image" tab, no longer works.  

When the buttons are pressed no additional output is shown in the cmd.exe window, except when stable diffusion is closed by pressing ctrl + C.

****Interrupted with signal 2 in <frame at 0x0000026F9AF7E990, file 'E:\\Automatic1111\\stable-diffusion-webui\\webui.py', line 209, code wait_on_server>**
Terminate batch job (Y/N)?**

- I decided to disable all other extensions to see if there was a conflict. The issue still persists.
- Deleted the venv folder.  The issue still persists.

```
Already up to date.
venv "E:\Automatic1111\stable-diffusion-webui\venv\Scripts\Python.exe"
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Commit hash: 4c1ad743e3baf1246db0711aa0107debf036a12b
Installing requirements for Web UI
Fetching updates for midas...
Checking out commit for midas with hash: b845b78...

Launching Web UI with arguments: --medvram --xformers --theme dark
Loading weights [1d1e459f9f] from E:\Automatic1111\stable-diffusion-webui\models\Stable-diffusion\anything-v4.5.safetensors
Creating model from config: E:\Automatic1111\stable-diffusion-webui\configs\v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Applying xformers cross attention optimization.
Textual inversion embeddings loaded(6): bad-artist-anime, bad-artist, easynegative, pureerosface_v1, Style-Moana-neg, ulzzang-6500-v1.1
Textual inversion embeddings skipped(7): embellish1, embellish2, embellish3, nartfixer, nfixer, nfixernext, nrealfixer
Model loaded in 3.0s (load weights from disk: 0.7s, create model: 0.5s, apply weights to model: 0.8s, apply half(): 0.9s).
[tag-editor] Settings has been read from config.json
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Startup time: 23.0s (import torch: 5.1s, import gradio: 1.1s, import ldm: 0.3s, other imports: 1.5s, list extensions: 8.1s, setup codeformer: 0.1s, load scripts: 2.5s, load SD checkpoint: 3.2s, create ui: 0.8s, gradio launch: 0.1s).
[tag-editor] Loading dataset from E:\Artists\cool\Images\Revised Captions\Revised Images\1024
[tag-editor] Total 532 files under the directory including not image files.
[tag-editor] Loading Completed: 266 images found`
```

```
`To create a public link, set `share=True` in `launch()`.
Startup time: 23.0s (import torch: 5.1s, import gradio: 1.1s, import ldm: 0.3s, other imports: 1.5s, list extensions: 8.1s, setup codeformer: 0.1s, load scripts: 2.5s, load SD checkpoint: 3.2s, create ui: 0.8s, gradio launch: 0.1s).
[tag-editor] Loading dataset from E:\Artists\coolio\Images\Revised Captions\Revised Images\1024
[tag-editor] Total 532 files under the directory including not image files.
[tag-editor] Loading Completed: 266 images found
[tag-editor] Loading dataset from C:\Users\Vigilence\Pictures\art\thest
[tag-editor] Total 5 files under the directory including not image files.
[tag-editor] Loading Completed: 5 images found
[tag-editor] Loading dataset from C:\Users\Vigilence\Pictures\art\thest
[tag-editor] Total 5 files under the directory including not image files.
[tag-editor] Backup text files: 0/3 under C:\Users\Vigilence\Pictures\art\thest
[tag-editor] Saved text files: 3/3 under C:\Users\Vigilence\Pictures\art\thest
[tag-editor] Loading Completed: 5 images found
[tag-editor] Backup text files: 0/5 under C:\Users\Vigilence\Pictures\art\thest
[tag-editor] Saved text files: 5/5 under C:\Users\Vigilence\Pictures\art\thest
[tag-editor] Loading dataset from C:\Users\Vigilence\Pictures\art\thest
[tag-editor] Total 10 files under the directory including not image files.
[tag-editor] Loading Completed: 5 images found
[tag-editor] Backup text files: 0/5 under C:\Users\Vigilence\Pictures\art\thest
[tag-editor] Saved text files: 5/5 under C:\Users\Vigilence\Pictures\art\thest
**Interrupted with signal 2 in <frame at 0x0000026F9AF7E990, file 'E:\\Automatic1111\\stable-diffusion-webui\\webui.py', line 209, code wait_on_server>**
Terminate batch job (Y/N)?`
```

**Comment by Vigilence** [comment]
> > After the newest update the "Read caption from selected image" and "Interrogate selected image" sub tab, which is under the "Edit caption from selected image" tab, no longer works.
> > When the buttons are pressed no additional output is shown in the cmd.exe window, except when stable diffusion is closed by pressing ctrl + C.
> 
> Does "no longer works" mean that nothing is output to the browser? And does "no additional output" mean that what should be displayed is not? (in most cases, you will not see anything in cmd.exe while editing tags.)
> 
> If you see anything on the javascript console when the error occurs, can you send me the log?
> 
> The same settings seem to work well in my environment. (The log `load checkpoint from C:\…` is when I used the BLIP and other interrogators.) ![ss2](https://user-images.githubusercontent.com/116595002/227889726-916e8389-982d-44bb-9c20-0dea8dc8f9f5.png)

Yes, no output is shown in the browser or the cmd.exe window when in those two sub tabs.  I am attempting to delete the folder and retry to see if this fixes the issue.  Can you share where I would find the log?

Thanks.

**Comment by toshiaki1729** [comment]
> Can you share where I would find the log?

You can see by pushing F12 mostly (developer tools).

(Google Chrome)
![ss3](https://user-images.githubusercontent.com/116595002/228100631-42e33079-af33-49f4-b84d-e3b50b85b6c2.png)
In my environment, when it works well, most of the log is saying about translation or something I don't know.

**Comment by Vigilence** [comment]
Here is a screen shot of the console for my browser (brave).  I noticed it keeps saying blocked by client, so I tried again in private mode and the issue disappears.  I then tried in edge and the extension loads perfectly.  Seems the new automatic1111 no longer works well with with one of my extensions.  I checked and all my ad blockers are disabled, so i am not sure which one it could be.

**Brave Browser**
![2023-03-27_21-40-47](https://user-images.githubusercontent.com/22781570/228105156-9eff0fac-1699-41ef-a832-29bb1564fa49.jpg)
![2023-03-27_21-40-59](https://user-images.githubusercontent.com/22781570/228105168-e03261a3-5dc6-4bcb-92c9-f82386815ea8.jpg)

**Brave Browser Private Mode**
![2023-03-27_21-44-24](https://user-images.githubusercontent.com/22781570/228105272-0847df1e-7516-4a1a-a746-ec7aa5ae0cc4.jpg)
[127.0.0.1-1679968019776.log](https://github.com/toshiaki1729/stable-diffusion-webui-dataset-tag-editor/files/11084406/127.0.0.1-1679968019776.log)

**Comment by LiJT** [comment]
I have the same issue, this plugin can no longer work to [Interrogate] selected image anymore, exactly as what you described....Thats the shame, this is my No1 tool to batch interrogate

**Comment by toshiaki1729** [comment]
For first aid, I'm going to focus on standalone tag-editor with old gradio (v3.22.1), which is working well widely.
Can you please use old tag-editor (v0.1.2) from old webUI, till the standalone version to be released?

**Comment by Vigilence** [comment]
> I have the same issue, this plugin can no longer work to [Interrogate] selected image anymore, exactly as what you described....Thats the shame, this is my No1 tool to batch interrogate

I fixed the issue by trying in microsoft edge, private mode, as well as disabling all extensions until I figured which could be an issue.  I am using both the updated automatic1111 and the newest dataset tag editor with no problems.  

**I can recommend a few solutions to see what the issue is:**

- Check your ad blockers and disable them for automatic1111's url (http://127.0.0.1:7860/ or whatever you have it configured as).
- Try using automatic1111 in a private window or in a different browser (also private window) such as Microsoft edge.
- Disable all your other installed extensions (in automatic1111) and restart automatic1111 (close the cmd.exe window and relaunch).
- Test the dataset tag editor, if it works then add one of your previously enabled extensions. Just one, then close automatic1111 (cmd.exe window) and relaunch. Test dataset tag editor and see if it works. If it works then repeat step 3 until you get to the extension that makes dataset tag editor to break.
- Last resort would be to disable all extensions, delete the venv folder, and then enable dataset tag editor by itself.  If it doesn't work its most likely the browser being used.  If it does work then enable one single extension, close automatic1111 (cmd.exe window), and relaunch.  If dataset tag editor works, then enable another extension and repeat the process, until you go enable each of your extensions (one by one), or enable an extension that breaks dataset tag editor.

Following these steps I figured it was brave browser, even in private mode, that was the issue.  Microsoft edge is now being used by me, with no issues and faster loading.

**Comment by LiJT** [comment]
> @LiJT For first aid, I'm going to focus on making standalone tag-editor with old gradio (v3.22.1), which is working well widely. Can you please use old tag-editor (v0.1.2) from old webUI, till the release of standalone version?

Thank you very much, yeah I m currently using the old version of automatic1111, therefore the old tag-editor 0.1.2 did the trick!

**Comment by LiJT** [comment]
> > I have the same issue, this plugin can no longer work to [Interrogate] selected image anymore, exactly as what you described....Thats the shame, this is my No1 tool to batch interrogate
> 
> I fixed the issue by trying in microsoft edge, private mode, as well as disabling all extensions until I figured which could be an issue. I am using both the updated automatic1111 and the newest dataset tag editor with no problems.
> 
> **I can recommend a few solutions to see what the issue is:**
> 
> * Check your ad blockers and disable them for automatic1111's url (http://127.0.0.1:7860/ or whatever you have it configured as).
> * Try using automatic1111 in a private window or in a different browser (also private window) such as Microsoft edge.
> * Disable all your other installed extensions (in automatic1111) and restart automatic1111 (close the cmd.exe window and relaunch).
> * Test the dataset tag editor, if it works then add one of your previously enabled extensions. Just one, then close automatic1111 (cmd.exe window) and relaunch. Test dataset tag editor and see if it works. If it works then repeat step 3 until you get to the extension that makes dataset tag editor to break.
> * Last resort would be to disable all extensions, delete the venv folder, and then enable dataset tag editor by itself.  If it doesn't work its most likely the browser being used.  If it does work then enable one single extension, close automatic1111 (cmd.exe window), and relaunch.  If dataset tag editor works, then enable another extension and repeat the process, until you go enable each of your extensions (one by one), or enable an extension that breaks dataset tag editor.
> 
> **Following these steps I figured it was brave browser (_same engine as chrome_), even in private mode, that was the issue. Microsoft edge is now being used by me, with no issues and faster loading.**

Wow thank you so much, When I upgrade my automatic1111 to the newest version i will follow ur guide, i m using Chrome as well, there must be some problem with it using the latest Gradio....

**Comment by crackfoo** [comment]
yes, this is broken for me using chrome has well. edge works. It would be nice to figure out what's wrong with chrome? I don't get errors in chrome, it just doesn't load the captions or interrogator. In chrome, the interrogator works in img2img and the `tagger` extension so hopefully it can be fixed here too.

thanks!
