### ISSUE TITLE
Image selection does not work

### ISSUE THREAD

**Issue by Best-by-feb132024** [toshiaki1729/stable-diffusion-webui-dataset-tag-editor#67]
Images are unable to be selected on any tab of the UI

eg: on the filter by tags tab filter buttons do not work

Selecting a filter for arrow does not filter down to only 1 image

![](https://i.imgur.com/F0dy4cY.png)

![](https://i.imgur.com/hRlJuTV.png)

eg: on the edit caption tab, captions are not read in because images are unable to be selected

![](https://i.imgur.com/V2u0VmQ.png)

**Comment by ride5k** [comment]
when attempting the above commands, the following results:

`T:\auto1111\stable-diffusion-webui-directml\extensions\stable-diffusion-webui-dataset-tag-editor>git fetch --tags

T:\auto1111\stable-diffusion-webui-directml\extensions\stable-diffusion-webui-dataset-tag-editor>git checkout tags/v0.x.x
error: pathspec 'tags/v0.x.x' did not match any file(s) known to git`

any assistance appreciated!

**Comment by toshiaki1729** [comment]
@ride5k 
v0.x.x need to be replaced with some valid version like v0.1.2 .
https://github.com/toshiaki1729/stable-diffusion-webui-dataset-tag-editor/releases

**Comment by Best-by-feb132024** [comment]
Update: seems fixed for me. Seems like updating my webui fixed it

**Comment by Kadah** [comment]
Updating A1111 past the gradio update fixed selection not working for me.

Am noticing that there is some latency when adding selection to filter, and sometimes the wrong image gets added.

When in zoomed view, next/previous image nav ignores current currently filtered images and instead goes to next/previous image in the whole data set..

**Comment by tenabraex** [comment]
Dear maintainer, please save us :D

**Comment by toshiaki1729** [comment]
https://github.com/toshiaki1729/dataset-tag-editor-standalone
Standalone Version is released (https://github.com/toshiaki1729/stable-diffusion-webui-dataset-tag-editor/issues/65#issuecomment-1529001674 for detail)
Still WIP but this may help you.
