### ISSUE TITLE
unexpected keyword argument 'prepend'

### ISSUE THREAD

**Issue by crackfoo** [toshiaki1729/stable-diffusion-webui-dataset-tag-editor#7]
Hi, 

After loading a dataset, using CLIP. I try to save the initial captions but the error below happens:

`TypeError: DatasetTagEditor.replace_tags() got an unexpected keyword argument 'prepend'`

I tried with and without "prepend addition tags" checked.

**Comment by toshiaki1729** [comment]
@crackfoo 
Really sorry for inconvenience!
I forgot replacing the argument name of the function...

**Comment by crackfoo** [comment]
thanks, it's no problem. I see you re-opened, as I was about to say it still happens even after the update.

**Comment by toshiaki1729** [comment]
> thanks, it's no problem. I see you re-opened, as I was about to say it still happens even after the update.
I reopened in the meaning of adding test framework to avoid this kind of bug.
Still happen in ba5c22c1b0be4e35d6fac9f43579daf2d7ba2a2b?

**Comment by toshiaki1729** [comment]
I think webUI reloads only the script directly under script folders using restart button in Extensions tab.
The file causing problem is not, so the restarting webUI will fix the problem... I hope so.

**Comment by crackfoo** [comment]
now the images don't get displayed in the webUI. the cmd window says it's
loaded x # of images but nothing is showing up... and no error otherwise...

applied latest updates since last mention and restarted auto's webui
completely.

Total 26 files under the directory including not image files.
Loading Completed.

[image: image.png]

**Comment by crackfoo** [comment]
hrm it does load fine on sets I've done before.  I'll bang away at it and
see if I can find a reason the other one I was trying isn't loading... it
does have a lot more images but I had already did the initial CLIP
import of that set and saved the txt files so not sure why it's not loading
back atm.

**Comment by toshiaki1729** [comment]
I found the Pillow Image.registered_extensions() returns only extension names related to PNG...
It will be redundant loading method but I will revert change in 73ed887e58114230fca0eb724e6925207b5663f8.

**Comment by crackfoo** [comment]
seems there must have been something in the txt file(s) of the dataset I was trying. I deleted them all and was able to re-generated and edit just fine afterwards. 

thanks!
