### ISSUE TITLE
sorting tags to be saved in to txt files

### ISSUE THREAD

**Issue by coudys** [toshiaki1729/stable-diffusion-webui-dataset-tag-editor#72]
When creating txt files at the end, the sorting of captions isn't optimal.

batch edit captions > extras > Sort tags in the images displayed. > frequency (if same frequency, alphabetical order as next)

example below:

frequency sorting:
1girl [107], brown_hair [107], realistic [107], woman [107], solo [105], long_hair [88]

class identifier for TI for example (a woman) sorting expected:
woman [107], 1girl [107], realistic [107], brown_hair [107], solo [105], long_hair [88]

applied workarounds:
changed tag "woman" to "a woman". This moved "a woman" tag to second position after 1girl. Not sure if I need "1girl" or "a woman" as first tag.

proposed solutions:
1. adding weights to tags within dataset tag editor
2. adding selected tags to extra sorting order group (prepend always to the beginning)

thank you.

**Comment by toshiaki1729** [comment]
Regex is useful for this kind of things.
The following is an example of moving the "1boy" tag to the first position in the caption.

![ss](https://user-images.githubusercontent.com/116595002/230067894-7eeef191-5e45-48a5-aa4b-bd7a1a7c0b05.png)

**Comment by coudys** [comment]
Thank you, gonna try that.
