### ISSUE TITLE
cannt load after auto1111 updated to v1.1

### ISSUE THREAD

**Issue by zark119** [toshiaki1729/stable-diffusion-webui-dataset-tag-editor#77]
Error executing callback ui_tabs_callback for C:\Users\zach1\stable-diffusion-webui\extensions\stable-diffusion-webui-dataset-tag-editor\scripts\main.py
Traceback (most recent call last):
  File "C:\Users\zach1\stable-diffusion-webui\modules\script_callbacks.py", line 134, in ui_tabs_callback
    res += c.callback() or []
  File "C:\Users\zach1\stable-diffusion-webui\extensions\stable-diffusion-webui-dataset-tag-editor\scripts\main.py", line 332, in on_ui_tabs
    ui.batch_edit_captions.set_callbacks(o_update_filter_and_gallery, ui.load_dataset, ui.filter_by_tags, get_filters, update_filter_and_gallery)
  File "C:\Users\zach1\stable-diffusion-webui\extensions\stable-diffusion-webui-dataset-tag-editor\scripts\ui\tab_batch_edit_captions.py", line 152, in set_callbacks
    self.tag_select_ui_remove.set_callbacks()
  File "C:\Users\zach1\stable-diffusion-webui\extensions\stable-diffusion-webui-dataset-tag-editor\scripts\ui\block_tag_select.py", line 54, in set_callbacks
    self.btn_deselect_visibles.click(fn=self.btn_deselect_visibles_clicked, inputs=self.cbg_tags, outputs=self.cbg_tags)
  File "C:\Users\zach1\stable-diffusion-webui\venv\lib\site-packages\gradio\events.py", line 132, in __call__
    dep, dep_index = self.trigger.set_event_trigger(
  File "C:\Users\zach1\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 217, in set_event_trigger
    check_function_inputs_match(fn, inputs, inputs_as_dict)
  File "C:\Users\zach1\stable-diffusion-webui\venv\lib\site-packages\gradio\utils.py", line 869, in check_function_inputs_match
    if not is_special_typed_parameter(name):
  File "C:\Users\zach1\stable-diffusion-webui\venv\lib\site-packages\gradio\utils.py", line 858, in is_special_typed_parameter
    is_event_data = issubclass(parameter_types.get(name, int), EventData)
TypeError: issubclass() arg 1 must be a class

**Comment by Mike1932** [comment]
Same issue.

**Comment by iconnoci** [comment]
Same issue.

**Comment by BorzoiEnjoyer** [comment]
Same here, i fixed the issue with a bit of GPT magic

By changing code in 851 line *vevn/Lib/Site-Packages/gradio/utils.py

from

    def is_special_typed_parameter(name):
        from gradio.helpers import EventData
        from gradio.routes import Request

        """Checks if parameter has a type hint designating it as a gr.Request or gr.EventData"""
        is_request = parameter_types.get(name, "") == Request
        # use int in the fall-back as that will always be false
        is_event_data = issubclass(parameter_types.get(name, int), EventData)
        return is_request or is_event_data

To

    def is_special_typed_parameter(name):
        from gradio.helpers import EventData
        from gradio.routes import Request

        """Checks if parameter has a type hint designating it as a gr.Request or gr.EventData"""
        parameter_type = parameter_types.get(name, None)
        is_request = parameter_type == Request
        is_event_data = False
        if parameter_type and isinstance(parameter_type, type):
            is_event_data = issubclass(parameter_type, EventData)
        return is_request or is_event_data

**Comment by YKefasu** [comment]
same on Vlad fork Version: eaea88a Mon May 1 21:03:08 2023 -0400

```
Loading theme: gradio/default
executing callback: C:\New folder\automatic\extensions\stable-diffusion-webui-dataset-tag-editor\scripts\main.py
ui_tabs_callback: TypeError
╭───────────────────────────────────────── Traceback (most recent call last) ──────────────────────────────────────────╮
│ C:\New folder\automatic\modules\script_callbacks.py:142 in ui_tabs_callback                                          │
│                                                                                                                      │
│   141 │   │   try:                                                                                                   │
│ ❱ 142 │   │   │   res += c.callback() or []                                                                          │
│   143 │   │   except Exception as e:                                                                                 │
│                                                                                                                      │
│ C:\New folder\automatic\extensions\stable-diffusion-webui-dataset-tag-editor\scripts\main.py:332 in on_ui_tabs       │
│                                                                                                                      │
│   331 │   │   ui.filter_by_selection.set_callbacks(o_update_filter_and_gallery, ui.dataset_gal                       │
│ ❱ 332 │   │   ui.batch_edit_captions.set_callbacks(o_update_filter_and_gallery, ui.load_datase                       │
│   333 │   │   ui.edit_caption_of_selected_image.set_callbacks(o_update_filter_and_gallery, ui.                       │
│                                                                                                                      │
│                                               ... 4 frames hidden ...                                                │
│                                                                                                                      │
│ C:\New folder\automatic\venv\lib\site-packages\gradio\utils.py:869 in check_function_inputs_match                    │
│                                                                                                                      │
│    868 │   │   if param.kind in [param.POSITIONAL_ONLY, param.POSITIONAL_OR_KEYWORD]:                                │
│ ❱  869 │   │   │   if not is_special_typed_parameter(name):                                                          │
│    870 │   │   │   │   if not has_default:                                                                           │
│                                                                                                                      │
│ C:\New folder\automatic\venv\lib\site-packages\gradio\utils.py:858 in is_special_typed_parameter                     │
│                                                                                                                      │
│    857 │   │   # use int in the fall-back as that will always be false                                               │
│ ❱  858 │   │   is_event_data = issubclass(parameter_types.get(name, int), EventData)                                 │
│    859 │   │   return is_request or is_event_data                                                                    │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
TypeError: issubclass() arg 1 must be a class
Running on local URL:  http://127.0.0.1:7861
```

**Comment by toshiaki1729** [comment]
gradio update, came across to another bug.
It seems just the same thing as #62

**Comment by toshiaki1729** [comment]
Can I turn of compatibility with old Python<=3.8?

**Comment by toshiaki1729** [comment]
Whit small fix, working  on the latest SD webUI in my environment.

![ss](https://user-images.githubusercontent.com/116595002/235650794-92479cdf-3413-400e-a8de-22abe0c7e7e6.png)

**Comment by toshiaki1729** [comment]
Isn't it working much faster than the previous gradio 3.23.0?
good boy gradio 3.28.1

**Comment by gydmg** [comment]
this is the error on broswer
python:3.10.11  •  torch: 2.0.0+cu118  •  xformers: 0.0.19  •  gradio: 3.28.1  •  commit: [5ab7f213]

Uncaught (in promise) TypeError: Cannot read properties of null (reading 'value')
    at setup (tagAutocomplete.js?1677481088.0:814:38)
