### ISSUE TITLE
Deepdanbooru changes

### ISSUE THREAD

**Issue by crackfoo** [toshiaki1729/stable-diffusion-webui-dataset-tag-editor#9]
Hi, 
Seems there are some changes on auto's repo for deepdanbooru and now it's not possible using your editor.

However it's still in a broken state on auto's untill a pending PR get merged.

https://github.com/AUTOMATIC1111/stable-diffusion-webui/pull/4913

Just FYI here for when it's fixed

**Comment by toshiaki1729** [comment]
trying to change deepbooru codes since it's modules are deprecated.

**Comment by toshiaki1729** [comment]
The issue seems to be fixed on this extension as long as I tested.
I hope so...

**Comment by crackfoo** [comment]
I still seem to get an error.

`  File "C:\sd\forks\auto1111\extensions\stable-diffusion-webui-dataset-tag-editor\scripts\main.py", line 251, in interrogate_selected_image_booru
    return interrogate_image_booru(selected_image_path)
  File "C:\sd\forks\auto1111\extensions\stable-diffusion-webui-dataset-tag-editor\scripts\dataset_tag_editor\dataset_tag_editor.py", line 37, in interrogate_image_booru
    return deepbooru.get_deepbooru_tags(img)
AttributeError: module 'modules.deepbooru' has no attribute 'get_deepbooru_tags'`

**Comment by crackfoo** [comment]
To be more specific, booru works when doing initial load and choosing "Use DeepDanbooru" but when on the "Interrogate Selected Image" tab, it's broken

**Comment by toshiaki1729** [comment]
@crackfoo 
thank you so much

**Comment by crackfoo** [comment]
Thanks so much, works great now!
