### ISSUE TITLE
Selecting the "If empty" option runs taggers despite already existing captions.

### ISSUE THREAD

**Issue by knzro** [toshiaki1729/stable-diffusion-webui-dataset-tag-editor#97]
**Describe the bug**
When selecting Using interrogator caption If empty is running the interrogators and appending the tags despite the images already having captions.

**To Reproduce**
1. Select use interrogator if empty .
2. fill all required fields.
3. click load.
4. Validate caption file exists.
5. Click unload.
6. Click load.

**Expected behavior**
It was expected that no extra tags where added when the dataset is loaded the second time, instead all images are tagged again appending the tags as in Append mode.

**Screenshots**
![image](https://github.com/toshiaki1729/stable-diffusion-webui-dataset-tag-editor/assets/83365874/0f7bac83-e37f-43a1-bef4-dd1137936411)
![image](https://github.com/toshiaki1729/stable-diffusion-webui-dataset-tag-editor/assets/83365874/fa42e60f-4f37-4629-b643-985eca17549e)

**Environment (please complete the following information):**
 - windows
 - firefox
 - v1.9.3, by AUTOMATIC1111]
 - 0.3.2

**Comment by toshiaki1729** [comment]
Thank you for your report!
